/**
 * API Endpoints Reference
 * This file stores all API base paths and endpoint patterns for internal reference.
 * These are NOT displayed to end users — they exist for easy updates when routes change.
 */

export const API_BASE = {
  INCUBATION_PORTAL: "/api/incubation-portal",
  STARTUP_PORTAL: "/api/startup-portal",
  MENTOR: "/api/mentor",
  ECOSYSTEM: "/api/ecosystem",
  SUPER_ADMIN: "/api/super-admin",
  PUBLIC: "/api",
};

export const INCUBATION_ENDPOINTS = {
  TENANT: {
    GET_INFO: "/tenant/info",
    UPDATE_PROFILE: "/tenant/profile",
    FETCH_MODULES: "/fetch-modules-for-tenant",
  },
  USER_MANAGEMENT: {
    CREATE_USER: "/create-user",
    GET_USERS: "/user/all",
    GET_TEAM_MEMBERS: "/user/team-members",
    GET_USER_DETAILS: "/user/:id",
    UPDATE_USER: "/user/:id",
  },
  ROLES: {
    CREATE: "/roles/create",
    UPDATE: "/roles/update",
    GET_ALL: "/roles/all",
    GET_DROPDOWN: "/roles/dropdown",
    GET_MODULES: "/roles/available-modules",
  },
  PROGRAM_CREATION: {
    CREATE_PROGRAM: "/program/create-program",
    GET_ALL_PROGRAMS: "/program/get-all-programs",
    GET_PROGRAM_DETAIL: "/program/get-program-detail/:id",
    UPDATE_PROGRAM: "/program/update-program-detail/:id",
    CREATE_SCHEME_TYPE: "/program/scheme-type",
    SEARCH_SCHEME_TYPES: "/program/scheme-types",
    CREATE_GOVERNING_BODY: "/program/governing-body",
    SEARCH_GOVERNING_BODIES: "/program/governing-bodies",
    CREATE_SCHEME_QUESTION: "/program/scheme-question",
    UPDATE_SCHEME_QUESTION: "/program/scheme-question/:id",
    DELETE_SCHEME_QUESTION: "/program/scheme-question/:id",
    CREATE_EVALUATION_QUESTION: "/evaluation-question/create",
    UPDATE_EVALUATION_QUESTION: "/evaluation-question/update/:id",
    DELETE_EVALUATION_QUESTION: "/evaluation-question/delete/:id",
    REORDER_EVALUATION_QUESTIONS: "/evaluation-question/reorder",
    TOGGLE_EVALUATION_ACTIVE: "/evaluation-question/toggle-active/:id",
  },
  PROGRAM_MANAGEMENT: {
    GET_REGISTRATIONS: "/program/:programId/registrations",
    GET_REGISTRATION_DETAIL: "/program/:programId/registrations/:registrationId",
    REQUEST_CHANGES: "/application/request-changes",
    CHANGE_APPLICATION_STATUS: "/application/:applicationId/change-status",
    REQUEST_DOCUMENT: "/application/request-document",
    SUBMIT_EVALUATION: "/application/submit-evaluation",
    GET_PENDING_CHANGES: "/application/:applicationId/changes/pending",
    GET_COMPLETED_CHANGES: "/application/:applicationId/changes/completed",
    GET_RECEIVED_CHANGES: "/application/:applicationId/changes/received",
    REREQUEST_CHANGE: "/application/:applicationId/changes/:changeRequestId/rerequest",
    APPROVE_CHANGE: "/application/:applicationId/changes/:changeRequestId/approve",
    REJECT_CHANGE: "/application/:applicationId/changes/:changeRequestId/reject",
    SEARCH_STARTUPS: "/startups/search",
    GET_STARTUP_DETAILS: "/startup/:startupId",
    ADD_EXISTING_STARTUP: "/program/:programId/add-existing-startup",
    CREATE_STARTUP: "/program/:programId/create-startup",
    REMOVE_STARTUP: "/program/:programId/startup/:startupId",
    GET_STARTUPS_BY_PROGRAM: "/programs/:programId/startups",
    GET_EVALUATIONS: "/application/:applicationId/evaluations",
    GET_EVALUATION_BY_ID: "/application/:applicationId/evaluation/:evaluationId",
    GET_EVALUATION_SUMMARY: "/application/:applicationId/evaluation-summary",
  },
  BATCHES: {
    CREATE: "/program/:programId/batch",
    GET_ALL: "/program/:programId/batches",
    GET_BY_ID: "/program/:programId/batch/:batchId",
    UPDATE: "/program/:programId/batch/:batchId",
    CHANGE_STATUS: "/program/:programId/batch/:batchId/status",
    DELETE: "/program/:programId/batch/:batchId",
    GET_REGISTRATIONS: "/program/:programId/batch/:batchId/registrations",
    GET_STARTUPS: "/program/:programId/batch/:batchId/startups",
    BULK_REGISTER: "/program/:programId/batch/:batchId/bulk-register",
  },
  STARTUP_MANAGEMENT: {
    GET_ALL: "/startups/list",
    GET_DETAILS: "/startups/:startupId",
    GET_OVERVIEW: "/startups/:startupId/overview",
    GET_FUNDING: "/startups/:startupId/funding",
    DISBURSE_FUNDING: "/startups/:startupId/disburse",
    GET_REGISTRATION: "/startups/:startupId/registration",
    GET_EVALUATIONS: "/startups/:startupId/evaluations",
    GET_OFFICE_ALLOCATIONS: "/startups/:startupId/office-allocations",
    GET_FACILITY_BOOKINGS: "/startups/:startupId/facility-bookings",
    GET_MENTORSHIPS: "/startups/:startupId/mentorships",
    GET_ASSOCIATIONS: "/startups/:startupId/associations",
  },
  OFFICE_SPACE: {
    CREATE: "/office/create",
    GET_ALL: "/office/list",
    GET_BY_ID: "/office/:officeId",
    UPDATE: "/office/:officeId",
    DELETE: "/office/:officeId",
    GET_PRICING: "/office/:officeId/pricing",
    ADD_PRICING: "/office/:officeId/pricing",
    UPDATE_PRICING: "/office/:officeId/pricing/:pricingId",
    DELETE_PRICING: "/office/:officeId/pricing/:pricingId",
    CHECK_AVAILABILITY: "/office/:officeId/availability",
    GET_CALENDAR: "/office/:officeId/calendar",
    GET_REQUESTS: "/office/requests",
    APPROVE_REQUEST: "/office/requests/:requestId/approve",
    REJECT_REQUEST: "/office/requests/:requestId/reject",
    ALLOCATE: "/office/allocate",
    GET_ALLOCATIONS: "/office/allocations",
    END_ALLOCATION: "/office/allocations/:allocationId/end",
    EXTEND_ALLOCATION: "/office/allocations/:allocationId/extend",
    GET_BOOKINGS: "/office/bookings",
    CONFIRM_BOOKING: "/office/bookings/:bookingId/confirm",
    CANCEL_BOOKING: "/office/bookings/:bookingId/cancel",
    GET_PAYMENTS: "/office/payments",
    INITIATE_REFUND: "/office/payments/:paymentId/refund",
    GET_DASHBOARD: "/office/dashboard",
  },
  FACILITY: {
    CREATE: "/facility/create",
    GET_ALL: "/facility/list",
    GET_BY_ID: "/facility/:facilityId",
    UPDATE: "/facility/:facilityId",
    DELETE: "/facility/:facilityId",
    CHECK_AVAILABILITY: "/facility/:facilityId/availability/:date",
    GET_REPORT: "/facility/report",
    GET_BOOKINGS: "/facility-booking/list",
    APPROVE_BOOKING: "/facility-booking/:bookingId/approve",
    REJECT_BOOKING: "/facility-booking/:bookingId/reject",
    CANCEL_BOOKING: "/facility-booking/:bookingId/cancel",
    RESCHEDULE_BOOKING: "/facility-booking/:bookingId/reschedule",
    GET_CALENDAR: "/facility-calendar",
    GET_TENANT_CALENDAR: "/facility-calendar/tenant",
    GET_USAGE: "/facility/usage",
  },
  FUNDING: {
    CREATE_SOURCE: "/funding/sources",
    GET_SOURCES: "/funding/sources",
    UPDATE_SOURCE: "/funding/sources/:sourceId",
    DELETE_SOURCE: "/funding/sources/:sourceId",
    ALLOCATE_TO_PROGRAM: "/funding/allocations",
    GET_ALLOCATIONS: "/funding/allocations",
    UPDATE_ALLOCATION: "/funding/allocations/:allocationId",
    DELETE_ALLOCATION: "/funding/allocations/:allocationId",
    CREATE_DISBURSEMENT: "/funding/disbursements",
    GET_DISBURSEMENTS: "/funding/disbursements",
    GET_DISBURSEMENT_BY_ID: "/funding/disbursements/:disbursementId",
    UPDATE_DISBURSEMENT_STATUS: "/funding/disbursements/:disbursementId/status",
    GET_PORTFOLIO: "/funding/portfolio",
    GET_OVERVIEW: "/funding/overview",
    GET_HISTORY: "/funding/history",
    GET_REQUESTS: "/funding/requests",
    APPROVE_REQUEST: "/funding/requests/:requestId/approve",
    REJECT_REQUEST: "/funding/requests/:requestId/reject",
  },
  ANNOUNCEMENT: {
    CREATE: "/announcement",
    GET_ALL: "/announcements",
    GET_BY_ID: "/announcement/:id",
    UPDATE: "/announcement/:id",
    DELETE: "/announcement/:id",
    PUBLISH: "/announcement/:id/publish",
    UNPUBLISH: "/announcement/:id/unpublish",
    PIN: "/announcement/:id/pin",
    UNPIN: "/announcement/:id/unpin",
    RESTORE: "/announcement/:id/restore",
    GET_STATS: "/announcement/:id/stats",
    GET_READS: "/announcement/:id/reads",
    ADD_TARGET: "/announcement/:id/targets",
    REMOVE_TARGET: "/announcement/:id/targets/:targetId",
    ADD_EXCLUSION: "/announcement/:id/exclusions",
    REMOVE_EXCLUSION: "/announcement/:id/exclusions/:exclusionId",
    ADD_ATTACHMENT: "/announcement/:id/attachments",
    REMOVE_ATTACHMENT: "/announcement/:id/attachments/:attachmentId",
  },
  TASK: {
    CREATE: "/task",
    GET_ALL: "/tasks",
    GET_BY_ID: "/task/:taskId",
    UPDATE: "/task/:taskId",
    DELETE: "/task/:taskId",
    GET_MY_TASKS: "/tasks/my-tasks",
    GET_CREATED_BY_ME: "/tasks/created-by-me",
    GET_OVERDUE: "/tasks/overdue",
    GET_STATS: "/tasks/stats",
    UPDATE_STATUS: "/task/:taskId/status",
    ASSIGN: "/task/:taskId/assign",
    GET_TEAM_MEMBERS: "/tasks/team-members",
    ADD_SUBTASK: "/task/:taskId/subtask",
    UPDATE_SUBTASK: "/task/:taskId/subtask/:subtaskId",
    TOGGLE_SUBTASK: "/task/:taskId/subtask/:subtaskId/toggle",
    DELETE_SUBTASK: "/task/:taskId/subtask/:subtaskId",
    REORDER_SUBTASKS: "/task/:taskId/subtasks/reorder",
    ADD_ATTACHMENT: "/task/:taskId/attachment",
    REMOVE_ATTACHMENT: "/task/:taskId/attachment/:attachmentId",
    ADD_COMMENT: "/task/:taskId/comment",
    UPDATE_COMMENT: "/task/:taskId/comment/:commentId",
    DELETE_COMMENT: "/task/:taskId/comment/:commentId",
  },
  MENTOR: {
    DISCOVER: "/mentor/discover",
    GET_ASSOCIATED: "/mentors/associated",
    GET_PENDING: "/mentor/applications",
    GET_PROFILE: "/mentor/:mentorId",
    INVITE: "/mentor/invite",
    APPROVE_ASSOCIATION: "/mentor-association/:associationId/approve",
    REJECT_ASSOCIATION: "/mentor-association/:associationId/reject",
    UPDATE_ASSOCIATION: "/mentor-association/:associationId",
    END_ASSOCIATION: "/mentor-association/:associationId/end",
    GET_SESSIONS: "/mentor-session/all",
    GET_SESSION_BY_ID: "/mentor-session/:sessionId",
    GET_ANALYTICS: "/mentor-analytics",
    GET_SPENDING: "/mentor-spending",
  },
  PANEL: {
    INVITE_MEMBER: "/panel/invite",
    GET_ALL_MEMBERS: "/panel/members",
    GET_PENDING_EVALUATIONS: "/panel/evaluations/pending",
    ASSIGN_TO_PROGRAM: "/panel/assign",
    REMOVE_FROM_PROGRAM: "/panel/remove",
    GET_PROGRAM_PANELS: "/program/:programId/panel",
    GET_EVALUATION_FORM: "/application/:applicationId/evaluation-form",
    SUBMIT_EVALUATION: "/application/:applicationId/evaluate",
    GET_EVALUATIONS: "/application/:applicationId/evaluations",
    GET_SUMMARY: "/application/:applicationId/evaluation-summary",
  },
  DATA_COLLECTION: {
    CREATE_REQUEST: "/program/:programId/data-collection-request",
    GET_REQUESTS: "/program/:programId/data-collection-requests",
    GET_BY_ID: "/data-collection-request/:requestId",
    UPDATE: "/data-collection-request/:requestId",
    REVIEW_SUBMISSION: "/data-collection-assignment/:assignmentId/review",
    CLOSE: "/data-collection-request/:requestId/close",
  },
  NOTIFICATION: {
    GET_ALL: "/notification",
    GET_UNREAD_COUNT: "/notification/unread-count",
    GET_PREFERENCES: "/notification/preferences",
    UPDATE_PREFERENCES: "/notification/preferences",
    MARK_ALL_READ: "/notification/read-all",
    CLEAR_ARCHIVED: "/notification/clear",
    GET_BY_ID: "/notification/:id",
    MARK_READ: "/notification/:id/read",
    ARCHIVE: "/notification/:id",
  },
  CHAT: {
    GET_SUPPORT_CHAT: "/support-chat",
    GET_CHAT_HISTORY: "/support-chat/history",
    MARK_READ: "/support-chat/read",
    GET_CONVERSATIONS: "/conversations",
    CREATE_CONVERSATION: "/conversation",
    GET_CONVERSATION: "/conversation/:conversationId",
    GET_MESSAGES: "/conversation/:conversationId/messages",
    SEND_MESSAGE: "/conversation/:conversationId/message",
    DELETE_MESSAGE: "/message/:messageId",
    EDIT_MESSAGE: "/message/:messageId",
    GET_UNREAD_COUNT: "/conversations/unread-count",
  },
  BILLING: {
    GET_DASHBOARD: "/billing/dashboard",
    CREATE_ORDER: "/billing/order",
    VERIFY_PAYMENT: "/billing/verify",
  },
  INVOICE: {
    GET_ALL: "/invoices",
    GET_BY_ID: "/invoices/:invoiceId",
  },
  ADDON_REQUEST: {
    GET_AVAILABLE: "/addons/available",
    SUBMIT_REQUEST: "/addons/request",
    GET_MY_REQUESTS: "/addons/my-requests",
    GET_REQUEST_DETAIL: "/addons/request/:requestId",
    CANCEL_REQUEST: "/addons/request/:requestId/cancel",
  },
  PUBLIC_REPOSITORY: {
    CREATE: "/repository",
    GET_ALL: "/repositories",
    GET_BY_ID: "/repository/:repositoryId",
    UPDATE: "/repository/:repositoryId",
    DELETE: "/repository/:repositoryId",
    REGENERATE_KEY: "/repository/:repositoryId/regenerate-key",
    GET_STATS: "/repository/:repositoryId/stats",
    ADD_ITEM: "/repository/:repositoryId/items",
    GET_ITEMS: "/repository/:repositoryId/items",
    BULK_ADD_ITEMS: "/repository/:repositoryId/items/bulk",
    BULK_DELETE_ITEMS: "/repository/:repositoryId/items/bulk-delete",
  },
  DASHBOARD: {
    GET_METRICS: "/dashboard/metrics",
    GET_APPLICATION_TIMELINE: "/dashboard/applications-timeline",
    GET_STARTUP_STAGES: "/dashboard/startup-stages",
  },
  PAYOUT_ACCOUNT: {
    GET: "/payout-account",
    CREATE: "/payout-account",
    UPDATE: "/payout-account",
    RESUBMIT: "/payout-account/resubmit",
    DELETE: "/payout-account",
    GET_DOCUMENTS: "/payout-account/documents",
    ADD_DOCUMENT: "/payout-account/documents",
    GET_STATUS: "/payout-account/status",
  },
  OFFICE_SUBSCRIPTION: {
    GET_ALL: "/office/subscriptions",
    GET_BY_ID: "/office/subscriptions/:bookingId",
    PAUSE: "/office/subscriptions/:bookingId/pause",
    RESUME: "/office/subscriptions/:bookingId/resume",
    CANCEL: "/office/subscriptions/:bookingId/cancel",
  },
  OFFICE_PAYOUT: {
    GET_ALL: "/office/payouts",
    GET_SUMMARY: "/office/payouts/summary",
    GET_BY_ID: "/office/payouts/:payoutId",
  },
};
