// EcoSync Website Keywords

export const ecosyncHomeKeywords = [
  "ecosync platform",
  "ecosync startup platform",
  "ecosync.co.in",
  "unified startup ecosystem",
  "startup collaboration platform",
  "founder mentor investor platform",
  "startup networking platform",
  "role based startup portal",
  "startup ecosystem software",
  "startup growth platform",
  "incubator management platform",
  "mentor startup matching",
  "investor startup discovery",
  "freelancer startup platform",
  "startup community platform",
  "startup acceleration platform",
  "digital startup infrastructure",
  "startup portal system",
  "ecosync by opernova",
  "opernova ecosync",
  "startup ecosystem india",
  "connect founders mentors investors",
  "startup incubator software",
  "startup mentor platform",
  "startup investment platform",
  "freelancer collaboration platform",
  "startup workspace platform",
  "startup event management",
  "startup community networking",
  "unified startup network",
];

export const ecosyncAboutKeywords = [
  "about ecosync",
  "ecosync mission",
  "ecosync team",
  "opernova technologies ecosync",
  "ecosync startup ecosystem story",
  "ecosync platform vision",
  "ecosync founding team",
  "unified startup hub about",
  "ecosync platform overview",
  "ecosync ecosystem architecture",
  "startup ecosystem platform india",
  "ecosync innovation platform",
  "ecosync digital infrastructure",
  "ecosync collaboration ecosystem",
  "ecosync growth methodology",
  "agile growth tech ecosync",
  "ecosync startup support",
  "ecosync platform features",
  "ecosync for entrepreneurs",
  "ecosync for incubators",
];

export const ecosyncContactKeywords = [
  "contact ecosync",
  "ecosync support",
  "ecosync help center",
  "ecosync customer support",
  "reach ecosync team",
  "ecosync inquiry",
  "ecosync platform support",
  "ecosync demo request",
  "ecosync partnership inquiry",
  "ecosync onboarding support",
  "ecosync startup consultation",
  "ecosync incubator inquiry",
  "ecosync investor inquiry",
  "ecosync mentor signup",
  "ecosync freelancer signup",
  "ecosync platform demo",
  "ecosync sales contact",
  "ecosync technical support",
  "ecosync feedback",
  "ecosync discord community",
];

export const ecosyncReferenceKeywords = [
  "ecosync documentation",
  "ecosync reference guide",
  "ecosync portal documentation",
  "ecosync platform guide",
  "ecosync user guide",
  "ecosync api reference",
  "ecosync feature documentation",
  "ecosync getting started",
  "ecosync onboarding guide",
  "ecosync platform walkthrough",
  "ecosync portal system guide",
  "ecosync role based portal docs",
  "ecosync startup tools guide",
  "ecosync mentor portal guide",
  "ecosync investor portal guide",
  "ecosync incubator portal guide",
  "ecosync freelancer portal guide",
  "ecosync workspace guide",
  "ecosync ecosystem reference",
  "ecosync platform architecture",
];

export const ecosyncIntroductionKeywords = [
  "ecosync introduction",
  "what is ecosync",
  "ecosync platform overview",
  "ecosync getting started",
  "ecosync startup ecosystem introduction",
  "ecosync unified platform",
  "ecosync role based system",
  "ecosync for founders",
  "ecosync for mentors",
  "ecosync for investors",
  "ecosync for freelancers",
  "ecosync for incubators",
  "how ecosync works",
  "ecosync platform benefits",
  "ecosync ecosystem explained",
];

export const ecosyncArchitectureKeywords = [
  "ecosync ecosystem architecture",
  "ecosync platform architecture",
  "ecosync system design",
  "ecosync infrastructure",
  "ecosync technical architecture",
  "ecosync scalable architecture",
  "ecosync microservices",
  "ecosync platform stack",
  "ecosync cloud architecture",
  "ecosync data architecture",
  "startup ecosystem architecture",
  "ecosync role based architecture",
  "ecosync portal architecture",
  "ecosync api architecture",
  "ecosync security architecture",
];

export const ecosyncStartupProfileKeywords = [
  "ecosync startup profile",
  "create startup profile ecosync",
  "startup profile management",
  "ecosync startup dashboard",
  "startup portfolio ecosync",
  "startup profile page",
  "ecosync company profile",
  "startup branding ecosync",
  "startup pitch profile",
  "ecosync startup onboarding",
  "startup visibility platform",
  "startup discovery profile",
  "ecosync startup showcase",
  "startup team profile",
  "startup metrics dashboard",
];

export const ecosyncApplicationsKeywords = [
  "ecosync startup applications",
  "apply to incubators ecosync",
  "startup application management",
  "ecosync application tracking",
  "incubator application platform",
  "accelerator application ecosync",
  "startup program applications",
  "ecosync application dashboard",
  "startup cohort applications",
  "ecosync batch applications",
  "startup application review",
  "ecosync application workflow",
  "startup funding applications",
  "ecosync grant applications",
  "startup competition applications",
];

export const ecosyncNetworkingKeywords = [
  "ecosync networking",
  "startup networking ecosync",
  "founder networking platform",
  "mentor networking ecosync",
  "investor networking platform",
  "ecosync smart networking",
  "ecosync discover people",
  "ecosync find cofounders",
  "startup community networking",
  "ecosync connection requests",
  "ecosync professional networking",
  "ecosync networking filters",
  "startup collaboration networking",
  "ecosync networking recommendations",
  "ecosync network growth",
];

export const ecosyncMentorshipKeywords = [
  "ecosync mentorship marketplace",
  "find mentor ecosync",
  "startup mentorship platform",
  "ecosync mentor matching",
  "mentor portal ecosync",
  "ecosync mentorship sessions",
  "startup mentor booking",
  "ecosync expert guidance",
  "ecosync mentor directory",
  "startup mentorship program",
  "ecosync 1on1 mentorship",
  "ecosync mentor reviews",
  "ecosync mentorship scheduling",
  "find startup mentor online",
  "ecosync mentor onboarding",
];

export const ecosyncSessionSchedulingKeywords = [
  "ecosync session scheduling",
  "book mentor session ecosync",
  "startup mentorship booking",
  "ecosync calendar scheduling",
  "ecosync session management",
  "mentor session booking platform",
  "ecosync appointment scheduling",
  "ecosync video session booking",
  "startup consultation scheduling",
  "ecosync availability management",
  "ecosync session reminders",
  "ecosync meeting scheduler",
  "startup expert session booking",
  "ecosync session tracking",
  "ecosync session feedback",
];

export const ecosyncStartupDiscoveryKeywords = [
  "ecosync startup discovery",
  "discover startups ecosync",
  "investor startup discovery",
  "ecosync startup scouting",
  "ecosync deal flow",
  "startup pipeline ecosync",
  "ecosync startup database",
  "ecosync startup search",
  "ecosync startup filters",
  "discover innovative startups",
  "ecosync startup recommendations",
  "ecosync curated startups",
  "investor deal sourcing ecosync",
  "ecosync startup marketplace",
  "ecosync startup trending",
];

export const ecosyncInvestmentKeywords = [
  "ecosync investment opportunities",
  "startup investment ecosync",
  "ecosync investor portal",
  "startup funding opportunities",
  "ecosync investment tracking",
  "ecosync portfolio management",
  "startup equity investment",
  "ecosync seed funding",
  "ecosync series a funding",
  "startup investment platform india",
  "ecosync investor dashboard",
  "ecosync cap table management",
  "startup valuation tracking",
  "ecosync investment analytics",
  "ecosync funding rounds",
];

export const ecosyncIncubatorKeywords = [
  "ecosync startup applications incubator",
  "incubator portal ecosync",
  "ecosync incubator management",
  "startup incubator platform",
  "ecosync accelerator portal",
  "ecosync cohort management",
  "incubator onboarding ecosync",
  "ecosync incubator dashboard",
  "startup batch management",
  "ecosync incubator evaluation",
  "ecosync program intake",
  "incubator startup tracking",
  "ecosync incubator analytics",
  "startup incubation software",
  "ecosync incubator workflow",
];

export const ecosyncEvaluationKeywords = [
  "ecosync evaluation panel",
  "startup evaluation ecosync",
  "ecosync review panel",
  "startup scoring system",
  "ecosync evaluation criteria",
  "startup assessment platform",
  "ecosync judge panel",
  "ecosync startup grading",
  "ecosync evaluation dashboard",
  "startup pitch evaluation",
  "ecosync evaluation workflow",
  "startup due diligence ecosync",
  "ecosync evaluation metrics",
  "ecosync reviewer management",
  "startup evaluation automation",
];

export const ecosyncProgramManagementKeywords = [
  "ecosync program management",
  "incubator program management",
  "ecosync cohort programs",
  "startup program tracking",
  "ecosync milestone management",
  "ecosync program dashboard",
  "startup accelerator programs",
  "ecosync curriculum management",
  "ecosync program analytics",
  "startup program scheduling",
  "ecosync batch programs",
  "incubator program software",
  "ecosync program workflows",
  "startup bootcamp management",
  "ecosync program reporting",
];

export const ecosyncFundingTrackingKeywords = [
  "ecosync funding tracking",
  "startup funding management",
  "ecosync grant tracking",
  "ecosync funding dashboard",
  "startup investment tracking",
  "ecosync disbursement tracking",
  "ecosync funding analytics",
  "startup funding rounds tracking",
  "ecosync financial management",
  "ecosync runway tracking",
  "startup burn rate tracking",
  "ecosync funding pipeline",
  "ecosync investor relations",
  "startup fundraising tracker",
  "ecosync funding milestones",
];

export const ecosyncTalentMarketplaceKeywords = [
  "ecosync talent marketplace",
  "freelancer marketplace ecosync",
  "ecosync hire freelancers",
  "startup talent platform",
  "ecosync freelancer portal",
  "ecosync gig marketplace",
  "startup freelancer matching",
  "ecosync talent discovery",
  "ecosync project based hiring",
  "startup talent acquisition",
  "ecosync skill based matching",
  "ecosync freelancer profiles",
  "startup contract work platform",
  "ecosync talent pool",
  "ecosync remote talent marketplace",
];

export const ecosyncProjectCollaborationKeywords = [
  "ecosync project collaboration",
  "startup project management",
  "ecosync team collaboration",
  "ecosync workspace collaboration",
  "startup task management ecosync",
  "ecosync collaboration rooms",
  "ecosync file sharing",
  "ecosync real time collaboration",
  "startup team workspace",
  "ecosync project dashboard",
  "ecosync brainstorming tools",
  "startup collaboration software",
  "ecosync project tracking",
  "ecosync team communication",
  "ecosync collaborative workspace",
];

export const ecosyncBlogKeywords = [
  "ecosync blog",
  "ecosync startup insights",
  "ecosync platform updates",
  "startup ecosystem articles",
  "ecosync news and updates",
  "ecosync founder stories",
  "startup growth strategies ecosync",
  "ecosync mentorship articles",
  "ecosync investment insights",
  "startup incubation articles",
  "ecosync platform tips",
  "ecosync community stories",
  "startup ecosystem trends",
  "ecosync product updates",
  "ecosync feature announcements",
  "startup networking tips",
  "ecosync best practices",
  "ecosync use cases",
  "startup collaboration articles",
  "ecosync industry insights",
];

export const ecosyncProductKeywords = [
  "ecosync product",
  "ecosync product features",
  "ecosync platform product",
  "ecosync saas product",
  "ecosync product overview",
  "ecosync product demo",
  "ecosync product pricing",
  "ecosync product roadmap",
  "ecosync product updates",
  "ecosync unified platform product",
  "ecosync startup product",
  "ecosync portal product",
  "ecosync enterprise product",
  "ecosync product for incubators",
  "ecosync product for investors",
];

// lib/referenceData.js

export const allReferencePages = [
  {
    slug: "introduction",
    title: "Introduction to EcoSync — How the Startup Ecosystem Works",
    description:
      "Get started with EcoSync. Understand how the platform connects founders, mentors, investors, freelancers, and incubators through personalized role-based portals.",
    keywords: [
      "ecosync introduction",
      "what is ecosync",
      "ecosync platform overview",
      "ecosync getting started",
      "ecosync unified platform",
      "ecosync role based system",
      "how ecosync works",
    ],
    image: "/reference/introduction.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "ecosystem-architecture",
    title: "EcoSync Ecosystem Architecture — Platform Infrastructure",
    description:
      "Explore EcoSync's scalable architecture designed to power startup ecosystems with role-based portals, real-time collaboration, and secure data infrastructure.",
    keywords: [
      "ecosync ecosystem architecture",
      "ecosync platform architecture",
      "ecosync system design",
      "ecosync infrastructure",
      "startup ecosystem architecture",
    ],
    image: "/reference/architecture.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "startup-profile",
    title: "Startup Profile — Showcase Your Venture on EcoSync",
    description:
      "Create and manage your startup profile on EcoSync. Showcase your team, metrics, and progress to attract mentors, investors, and collaborators.",
    keywords: [
      "ecosync startup profile",
      "create startup profile",
      "startup profile management",
      "startup portfolio ecosync",
      "startup discovery profile",
    ],
    image: "/reference/startup-profile.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "applications",
    title: "Startup Applications — Apply to Incubators & Programs on EcoSync",
    description:
      "Discover and apply to incubator programs, accelerators, and funding opportunities. Track your application status and manage submissions in one place.",
    keywords: [
      "ecosync startup applications",
      "apply to incubators",
      "startup application management",
      "incubator application platform",
      "startup program applications",
    ],
    image: "/reference/applications.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "networking",
    title: "Smart Networking — Discover Founders, Mentors & Investors",
    description:
      "Build meaningful connections with founders, mentors, investors, and freelancers. EcoSync's smart networking matches you with the right people in the ecosystem.",
    keywords: [
      "ecosync networking",
      "startup networking",
      "founder networking platform",
      "ecosync find cofounders",
      "startup community networking",
    ],
    image: "/reference/networking.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "mentorship-marketplace",
    title: "Mentorship Marketplace — Find Expert Mentors on EcoSync",
    description:
      "Browse and book sessions with experienced mentors. Get 1-on-1 guidance on strategy, product, fundraising, and growth through EcoSync's mentorship marketplace.",
    keywords: [
      "ecosync mentorship marketplace",
      "find mentor ecosync",
      "startup mentorship platform",
      "ecosync mentor matching",
      "ecosync mentorship sessions",
    ],
    image: "/reference/mentorship.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "session-scheduling",
    title: "Session Scheduling — Book Mentor & Expert Sessions on EcoSync",
    description:
      "Schedule mentorship sessions, consultations, and expert calls with EcoSync's integrated booking system. Manage availability, reminders, and feedback seamlessly.",
    keywords: [
      "ecosync session scheduling",
      "book mentor session",
      "startup mentorship booking",
      "ecosync calendar scheduling",
      "mentor session booking platform",
    ],
    image: "/reference/scheduling.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "startup-discovery",
    title: "Startup Discovery — Scout & Evaluate Startups on EcoSync",
    description:
      "Discover innovative startups through curated deal flow. Filter by sector, stage, and location to find investment-ready ventures on EcoSync.",
    keywords: [
      "ecosync startup discovery",
      "discover startups",
      "investor startup discovery",
      "ecosync deal flow",
      "startup pipeline ecosync",
    ],
    image: "/reference/discovery.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "investment-opportunities",
    title: "Investment Opportunities — Fund Startups Through EcoSync",
    description:
      "Explore startup investment opportunities on EcoSync. Track funding rounds, manage your portfolio, and connect directly with founders seeking capital.",
    keywords: [
      "ecosync investment opportunities",
      "startup investment",
      "ecosync investor portal",
      "startup funding opportunities",
      "ecosync portfolio management",
    ],
    image: "/reference/investment.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "startup-applications",
    title: "Incubator Portal — Manage Startup Applications on EcoSync",
    description:
      "Streamline your incubator's application process. Review, evaluate, and onboard startups with EcoSync's incubator management portal.",
    keywords: [
      "ecosync incubator portal",
      "incubator management",
      "startup application review",
      "ecosync cohort management",
      "incubator onboarding ecosync",
    ],
    image: "/reference/incubator.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "evaluation-panel",
    title: "Evaluation Panel — Score & Review Startups on EcoSync",
    description:
      "Run structured startup evaluations with customizable criteria, scoring rubrics, and reviewer panels. Streamline due diligence on EcoSync.",
    keywords: [
      "ecosync evaluation panel",
      "startup evaluation",
      "ecosync review panel",
      "startup scoring system",
      "startup assessment platform",
    ],
    image: "/reference/evaluation.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "program-management",
    title: "Program Management — Run Incubator Cohorts on EcoSync",
    description:
      "Manage incubator and accelerator programs end-to-end. Track milestones, schedule sessions, and monitor startup progress with EcoSync.",
    keywords: [
      "ecosync program management",
      "incubator program management",
      "ecosync cohort programs",
      "startup program tracking",
      "ecosync milestone management",
    ],
    image: "/reference/program.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "funding-tracking",
    title: "Funding Tracking — Monitor Startup Finances on EcoSync",
    description:
      "Track funding rounds, disbursements, grants, and runway. EcoSync gives incubators and investors real-time visibility into startup financial health.",
    keywords: [
      "ecosync funding tracking",
      "startup funding management",
      "ecosync grant tracking",
      "startup investment tracking",
      "ecosync runway tracking",
    ],
    image: "/reference/funding.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "talent-marketplace",
    title: "Talent Marketplace — Hire Freelancers & Experts on EcoSync",
    description:
      "Find skilled freelancers for your startup. Post projects, browse talent profiles, and hire on-demand through EcoSync's talent marketplace.",
    keywords: [
      "ecosync talent marketplace",
      "freelancer marketplace",
      "ecosync hire freelancers",
      "startup talent platform",
      "ecosync gig marketplace",
    ],
    image: "/reference/talent.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
  {
    slug: "project-collaboration",
    title: "Project Collaboration — Team Workspaces on EcoSync",
    description:
      "Collaborate with your team in shared workspaces. Manage tasks, share files, brainstorm ideas, and communicate in real-time on EcoSync.",
    keywords: [
      "ecosync project collaboration",
      "startup project management",
      "ecosync team collaboration",
      "ecosync workspace collaboration",
      "ecosync collaboration rooms",
    ],
    image: "/reference/collaboration.png",
    datePublished: "2026-01-15",
    dateModified: "2026-03-10",
  },
];
